### PR TITLE
Fix vulnerabilities

### LINKED ISSUE #30: Webhook server could not answer in time
**REPRODUCTION**
- certm-manager and its CRDs are deployed
- webhook and operator helm chart are deployed
- the webhook's and the operator's pods are in ready state 
- the attached Vertica descriptor is applied with the kubectl command: `kubectl -n <namespace> apply -f <path-to-the-attached-file>`
- The following error is raised by the kubernetes API:
```
Error from server (InternalError): error when creating "test-upgrade-vertica/test_vertica_oper.yaml": Internal error occurred: failed calling webhook "vverticadb2.kb.io": Post "https://verticadb-webhook-webhook-service.analytical-processing-database-precodereview-1081.svc:443/validate-vertica-com-v1beta1-verticadb?timeout=10s": dial tcp 10.99.146.222:443: connect: connection refused
```
- I tried to call the same command again and again and it was success after the 3rd call

The strange thing was that the webhook got the vertica descriptor, and a response was sent by the webhook (check the logs below). I guess there was a timeout between the webhook and the kubertetes API server, because I had to wait at least 1,5 sec to got any response, but I do not know how can I check it to give more details. If it was a timeout then it could be a wrong connection pool handling in the webhook or a wrong configuration in the kube-rbac-proxy.

webhook manager container log:
```
2021-08-11T10:54:35.861Z        DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/mutate-vertica-com-v1beta1-verticadb", "UID": "896bae9c-6be2-4259-8064-174092b89ce3", "kind": "vertica.com/v1beta1, Kind=VerticaDB", "resource": {"group":"vertica.com","version":"v1beta1","resource":"verticadbs"}}
2021-08-11T10:54:35.862Z        INFO    verticadb-resource      default {"name": "verticadb-upgrade-test"}
2021-08-11T10:54:35.863Z        DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/mutate-vertica-com-v1beta1-verticadb", "code": 200, "reason": "", "UID": "896bae9c-6be2-4259-8064-174092b89ce3", "allowed": true}
```

### PR DESCRIPTION
**Pull request by roypaulin**
This PR follows security vulnerabilities that  have been detected inside operator pods.
the highlights are:
-  upgrade operator-sdk  which leads to upgrade of go (v1.17), controller-gen (v0.8) and other packages as you can see here https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.17.0
- In this version of controller-gen trivialVersions and preserveUnknownFields are not supported anymore
- To install package we use go install instead of go get as using go get to build and install packages is deprecated and will not be possible from v1.18.
- setup-envtest.sh does not exist anymore in recent releases and has been replaced by setup-envtest package.

Closes #30

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -195,15 +195,21 @@ vet: ## Run go vet against code.
...
+export KUBEBUILDER_ASSETS=$(ENVTEST_ASSETS_DIR)/bin
+test: install-unittest-plugin manifests generate fmt vet lint get-go-junit-report setup-envtest
 	helm unittest --helm3 --output-type JUnit --output-file $(TMPDIR)/unit-tests.xml helm-charts/verticadb-operator
 	mkdir -p ${ENVTEST_ASSETS_DIR}
-	test -f ${ENVTEST_ASSETS_DIR}/setup-envtest.sh || curl -sSLo ${ENVTEST_ASSETS_DIR}/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.7.2/hack/setup-envtest.sh
+	mkdir -p ${ENVTEST_ASSETS_BIN_DIR}
+	mkdir -p ${KUBEBUILDER_ASSETS}
+	$(SETUP_ENVTEST) use --bin-dir $(ENVTEST_ASSETS_BIN_DIR)
+	find $(ENVTEST_ASSETS_BIN_DIR)/ -exec cp {} $(KUBEBUILDER_ASSETS)/ \;
+	sudo rm -r $(ENVTEST_ASSETS_BIN_DIR)
```
Comment (roypaulin) [inline Makefile:207]: I do not like this sudo. First I did not intend to add it but the github checks were failing. Using setup-envtest, the binaries are generated in <your-dir>/k8s/<version>. So I generated them in testbin/tmp/k8s/<version> them copy them to testbin/bin to then delete testbin/tmp.

File: Makefile [hunk 2]
```diff
@@ -421,7 +427,11 @@ KUBERNETES_SPLIT_YAML = $(shell pwd)/bin/kubernetes-split-yaml
 kubernetes-split-yaml: ## Download kubernetes-split-yaml locally if necessary.
 	$(call go-get-tool,$(KUBERNETES_SPLIT_YAML),github.com/mogensen/kubernetes-split-yaml@v0.3.0)
 
-# go-get-tool will 'go get' any package $2 and install it to $1.
+SETUP_ENVTEST = $(shell pwd)/bin/setup-envtest
```
Comment (spilchen) [inline Makefile:430]: We should follow what is done in the generated Makefile.  So this becomes `ENVTEST =` and the make target below becomes `envtest`.

File: scripts/gen-csv.sh [hunk 3]
```diff
@@ -72,3 +72,12 @@ $KUSTOMIZE build config/overlays/csv | $OPERATOR_SDK generate bundle -q --overwr
...
 sed -i "s/CREATED_AT_PLACEHOLDER/$(date +"%FT%H:%M:%SZ")/g" bundle/manifests/verticadb-operator.clusterserviceversion.yaml
 sed -i "s+OPERATOR_IMG_PLACEHOLDER+$(make echo-images | grep OPERATOR_IMG | cut -d'=' -f2)+g" bundle/manifests/verticadb-operator.clusterserviceversion.yaml
+
+# Add the supported versions at the end of annotations.yaml
+cat <<EOT >> bundle/metadata/annotations.yaml
+
+  # Annotation to specify the supported versions.
+  # This annotation has been added because for now, the operator does not work
+  # with versions lower than v4.8.
+  com.redhat.openshift.versions: "v4.8"
```
Comment (spilchen) [inline scripts/gen-csv.sh:82]: Does this mean we won't support 4.9?

**Review by spilchen — COMMENTED** [review]
I didn't see any evidence that we applied these upgrade steps.  We should apply them:
https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.11.0/#gov3-ansiblev1-helmv1-add-containerport-protocol-field-in-manifests
https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.16.0/#add-annotation-to-specify-the-default-container
https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.18.0/#support-image-digests-instead-of-tags

This upgrade was partially done:
https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.14.0/#upgrade-k8s-versions-to-use-122-golangv3

I didn't see any evidence that these ones were added
- ENVTEST_K8S_VERSION  (although the version has been bumped since then)
- Replace your admissionReviewVersions={v1,v1beta1} markers with admissionReviewVersions=v1

**Comment by spilchen** [comment]
We should add a changie entry too to indicate we moved to operator-sdk version 1.18.0

File: scripts/gen-csv.sh (hunk 3 above)
Comment (roypaulin) [reply scripts/gen-csv.sh:82]: No it means we support 4.8 and beyond.

File: Makefile (hunk 2 above)
Comment (roypaulin) [reply Makefile:430]: Yes it is definitely simpler like that. I will do that.

**Comment by roypaulin** [comment]
> I didn't see any evidence that we applied these upgrade steps. We should apply them: https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.11.0/#gov3-ansiblev1-helmv1-add-containerport-protocol-field-in-manifests https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.16.0/#add-annotation-to-specify-the-default-container https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.18.0/#support-image-digests-instead-of-tags
> 
> This upgrade was partially done: https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.14.0/#upgrade-k8s-versions-to-use-122-golangv3
> 
> I didn't see any evidence that these ones were added
> 
>     * ENVTEST_K8S_VERSION  (although the version has been bumped since then)
> 
>     * Replace your admissionReviewVersions={v1,v1beta1} markers with admissionReviewVersions=v1

Yes I oversimplified this upgrade. With such a big jump in version it is clear that intermediary upgrades should not be skipped. I will change that.

File: Makefile [hunk 4]
```diff
@@ -427,9 +432,10 @@ KUBERNETES_SPLIT_YAML = $(shell pwd)/bin/kubernetes-split-yaml
 kubernetes-split-yaml: ## Download kubernetes-split-yaml locally if necessary.
 	$(call go-get-tool,$(KUBERNETES_SPLIT_YAML),github.com/mogensen/kubernetes-split-yaml@v0.3.0)
 
-SETUP_ENVTEST = $(shell pwd)/bin/setup-envtest
-setup-envtest: ## Download setup-envtest that that manages binaries for envtest.
-	$(call go-get-tool,$(SETUP_ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest@latest)
+ENVTEST = $(shell pwd)/bin/setup-envtest
+.PHONY: envtest
+envtest: ## Download envtest-setup locally if necessary.
```
Comment (spilchen) [inline Makefile:437]: The comment should be "Download setup-envtest-setup locally if necessary."

File: config/webhook/manifests.yaml [hunk 5]
```diff
@@ -9,19 +7,13 @@ metadata:
...
   - v1
-  - v1beta1
   clientConfig:
     service:
       name: webhook-service
       namespace: system
       path: /mutate-vertica-com-v1beta1-verticadb
   failurePolicy: Fail
   name: mverticadb.kb.io
-  namespaceSelector:
```
[the remark this answers is not in the document]
Comment (roypaulin) [reply config/webhook/manifests.yaml:20]: Sorry what do you mean by is no longer generated? because with `controller-gen crd webhook ....` it automatically generates the file you see right now. Or do you mean we should still keep the part you highlighted and prevent this file to be re-generated each time?

[the remark this answers is not in the document]
Comment (spilchen) [reply config/webhook/manifests.yaml:20]: We changed this file to not be generated anymore.  We did this because we needed to add the namespace selector to it in order to get the webhook to work.  So, I think we still need that selector added.

File: config/webhook/manifests.yaml [hunk 6]
```diff
@@ -1,5 +1,3 @@
-# Originally generated via:
```
Comment (spilchen) [inline config/webhook/manifests.yaml:1]: Can we add this comment back?  And should we update the proper command to run to generate this file.  I think some of these parms were removed.

**Review by spilchen — COMMENTED** [review]
I think we can get rid of scripts/wait-for-webhook.sh.  The update to controller-runtime should have fixed that as it adds a true health check that `helm --wait` can depend on.

**Comment by spilchen** [comment]
The changes look good.  Lets create the changie entry.  And I will push it sometime next week once we have upgraded Go on our internal build machines.

**Comment by roypaulin** [comment]
I guess the Kind of changie is "Changed".

File: changes/unreleased/Changed-20220304-221506.yaml [hunk 7]
```diff
@@ -0,0 +1,5 @@
+kind: Changed
+body: Move to operator-sdk v1.18.0
+time: 2022-03-04T22:15:06.6959129+01:00
+custom:
+  Issue: "30"
```
Comment (spilchen) [inline changes/unreleased/Changed-20220304-221506.yaml:5]: We should use 165 as the issue number.  I typically try to link with the PR that pushed the change as that gives more context.
